export enum ThemeMutationTypes {
  SET_THEME = "SET_THEME",
  CHANGE_WIDTH = "CHANGE_WIDTH"
}

export enum DocumentMutationTypes {
  ADD_TUTORIAL = "ADDARTICLE",
  CHANGE_TUTORIAL = "CHANGETUTORIAL",
  REMOVE_TUTORIAL = "REMOVETURTORIAL"
}
